sudo: required
dist: trusty
language: ruby
rvm:
  - "1.9.3"
install:
  - sudo echo "deb http://download.virtualbox.org/virtualbox/debian trusty contrib" | sudo tee -a /etc/apt/sources.list
  - wget http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get -y install linux-headers-$(uname -r)
  - sudo apt-get -y install virtualbox-4.2
  - VBoxManage -v
script:
  - date
  - echo "--- END ---"
  - VBoxManage -v
